### ISSUE TITLE
Creating Custom Activities Recipe?

### ISSUE THREAD

**Issue by ahetawal** [mattcam/Salesforce-Marketing-Cloud-Developer-Edition-Recipes#3]
Hi,
This repo has been a life safer, helping to understand the MC apis. I was wondering if you have any plans to add a Recipe for adding Custom activities to JB, seems thats one of the most common use for 3rd party developers.

Thanks again,

**Comment by eliotharper** [comment]
Hi @ahetawal, thanks for your feedback. I've documented Custom Activities in my book [Journey Builder Developer's Guide](http://www.amazon.com/Journey-Builder-Developers-Guide-Harper/dp/099431180X/). There's also a repo with example app at https://github.com/sfmc-developer-advocates/custom-activity-deskapi-node

**Comment by ahetawal** [comment]
Great let me take a look. 
Thanks again for such a great resource.
