### ISSUE TITLE
Synchronized data extension - sendable data extension using filters

### ISSUE THREAD

**Issue by CarineG** [mattcam/Salesforce-Marketing-Cloud-Developer-Edition-Recipes#5]
I really like you step by step guides! I find them incredibly valuable and easy to interpret! I can't figure out how to get synchronized data into sendable data extensions using filters. I cant use queries so filters is my only option, Im not technical. Im wondering if you can make a recipe to show the steps - I think my mistake is the primary key that I am selecting. Also do you create a filtered data extension or a normal one? Thank you!

**Comment by mattcam** [comment]
Hello @CarineG and thanks for the question. Apologies for the delay in getting back to you. This is a really good question and it would be very interesting to find out about your progress. 

To help get this actioned I have added it to backlog of ideas for SFMC dev group https://github.com/mattcam/Salesforce-Marketing-Cloud-Developer-Edition-Recipes/issues/5

Also did you reach out on https://salesforce.stackexchange.com/ and was that helpful?
